# Form implementation generated from reading ui file '.\ui\.\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 592)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plotWidget = PlotWidget(parent=self.centralwidget)
        self.plotWidget.setObjectName("plotWidget")
        self.horizontalLayout.addWidget(self.plotWidget)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonFind = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonFind.setObjectName("pushButtonFind")
        self.verticalLayout.addWidget(self.pushButtonFind)
        self.pushButtonStart = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.verticalLayout.addWidget(self.pushButtonStart)
        self.pushButtonStop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.verticalLayout.addWidget(self.pushButtonStop)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBoxFormat = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBoxFormat.setObjectName("comboBoxFormat")
        self.comboBoxFormat.addItem("")
        self.comboBoxFormat.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxFormat)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButtonRecording = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonRecording.setObjectName("pushButtonRecording")
        self.verticalLayout.addWidget(self.pushButtonRecording)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonFind.setText(_translate("MainWindow", "Find"))
        self.pushButtonStart.setText(_translate("MainWindow", "Start"))
        self.pushButtonStop.setText(_translate("MainWindow", "Stop"))
        self.label.setText(_translate("MainWindow", "Format:"))
        self.comboBoxFormat.setItemText(0, _translate("MainWindow", "WFDB"))
        self.comboBoxFormat.setItemText(1, _translate("MainWindow", "EDF"))
        self.pushButtonRecording.setText(_translate("MainWindow", "Start Recording"))
from pyqtgraph import PlotWidget
